#Updated property: CRnumberFromDB
#Thu Nov 21 11:23:41 GMT+03:00 2024
#Config
CarFuelConsumptionTracker-URL=http://hiring.petroapp.com/test2.html
waitTime=10
Browser=Chrome

#Data
CompanyId_Prefix=COMP
Header=Car Fuel Consumption Tracker
#Locators#####
PageHeader_Locator=h1
AddRecordHeader_Locator=h3
CardNumber_Locator=//input[@name='carNumber']
fuelInLiters_Locator=//input[@name='fuelInLiters']
fuelCost_Locator=//input[@name='fuelCost']
fuelType_Locator=//input[@name='fuelType']
companyId_Locator=//input[@name='companyId']
Add_Locator=//button[@type='submit']
DatePickr_Locator=input[name='dateAndTime']
Grid_Locator=table.table-striped
Table_rows_locator=tr
Table_data_locator=td
DeleteBtn_Locator =//table//button[contains(text(), 'Delete')]

